### PR TITLE
Update comment to save dev time

### PR DESCRIPTION
**Pull request by apple-corps**
I found via source package to build via debian...

### CODE REVIEW

**Comment by gradinac** [comment]
Hey drocsid! Thank you very much for your contribution!
While I agree we can in theory use the distro's `libstdc++.a` (basically using the C standard as the compatibility layer), issues can arise in case it uses glibc-specific stuff/constants which can differ between libc distributions. Although I have not experienced it yet with `libstdc++.a`, I have with some other libraries (most of the time, it would be missing symbols).
See this: https://www.musl-libc.org/faq.html, it has a mention of `libstdc++.a`:
> Be aware that, "out of the box", the wrapper only supports C applications, not C++. This is because the C++ libraries and headers are missing from the musl include/library path. The existing libstdc++ is actually compatible with musl in most cases and could be used by copying it into the musl library path, but the C++ header files are usually not compatible. One option may be rebuilding just libstdc++ against musl; however, if C++ support is needed, it's recommended just to build a native toolchain targetting musl.

We can add your suggestion to the docs, but we should clearly mark it as having a potential to fail, preferably with this link provided.

**Comment by apple-corps** [comment]
@gradinac do you want me to merge and decorate on top of that? I took libstdc++.a from debian testing and built my static image. It was easier than figuring out how to build gcc for debian from the source packages...

**Comment by apple-corps** [comment]
@gradinac 

As an aside. When trying to start my static image and use ipv6 recently got:


```
java.net.SocketException: Protocol family unavailable
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_net_SocketException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
        at com.oracle.svm.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)
        at com.oracle.svm.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:801)
        at sun.nio.ch.Net.bind0(Net.java)
        at sun.nio.ch.Net.bind(Net.java:455)
        at sun.nio.ch.Net.bind(Net.java:447)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at java.nio.channels.ServerSocketChannel.bind(ServerSocketChannel.java:162)
        at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup.$anonfun$bind$1(NIO1SocketServerGroup.scala:217)
        at scala.util.Try$.apply(Try.scala:210)
        at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup.bind(NIO1SocketServerGroup.scala:216)
        at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup$$anon$1.bind(NIO1SocketServerGroup.scala:79)
        at org.http4s.server.blaze.BlazeServerBuilder.$anonfun$resource$5(BlazeServerBuilder.scala:341)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
        at cats.effect.IO$Map.apply(IO.scala:1504)
        at cats.effect.IO$Map.apply(IO.scala:1502)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:142)
        at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
        at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:88)
        at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
        at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:89)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:89)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:89)
        at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
        at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
        at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:69)
        at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:49)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
        at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
        at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:42)
        at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:32)
        at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:345)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:122)
        at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:359)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:380)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:323)
        at cats.effect.internals.IOShift$Tick.run(IOShift.scala:35)
        at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

but no issue if I remove the static and muslc... I think my other static image is running just find via ipv4...

**Comment by gradinac** [comment]
@drocsid 
> @gradinac do you want me to merge and decorate on top of that? I took libstdc++.a from debian testing and built my static image. It was easier than figuring out how to build gcc for debian from the source packages...

Sure, as long as the readme contains the warning in the end. I agree with you, it is much easier than building it from source - this repository actually does the building for you while reusing alpine's `libstdc++.a`, you can also find the pre-built libraries in the `release` section of this repo.

> @gradinac
> 
> As an aside. When trying to start my static image and use ipv6 recently got:
> 
> ```
> java.net.SocketException: Protocol family unavailable
>         at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_net_SocketException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
>         at com.oracle.svm.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)
>         at com.oracle.svm.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:801)
>         at sun.nio.ch.Net.bind0(Net.java)
>         at sun.nio.ch.Net.bind(Net.java:455)
>         at sun.nio.ch.Net.bind(Net.java:447)
>         at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
>         at java.nio.channels.ServerSocketChannel.bind(ServerSocketChannel.java:162)
>         at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup.$anonfun$bind$1(NIO1SocketServerGroup.scala:217)
>         at scala.util.Try$.apply(Try.scala:210)
>         at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup.bind(NIO1SocketServerGroup.scala:216)
>         at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup$$anon$1.bind(NIO1SocketServerGroup.scala:79)
>         at org.http4s.server.blaze.BlazeServerBuilder.$anonfun$resource$5(BlazeServerBuilder.scala:341)
>         at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
>         at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
>         at cats.effect.IO$Map.apply(IO.scala:1504)
>         at cats.effect.IO$Map.apply(IO.scala:1502)
>         at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:142)
>         at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
>         at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:88)
>         at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
>         at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
>         at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:89)
>         at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:89)
>         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
>         at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
>         at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:89)
>         at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
>         at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
>         at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:69)
>         at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:49)
>         at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
>         at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
>         at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:42)
>         at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:32)
>         at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:345)
>         at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:122)
>         at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:359)
>         at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:380)
>         at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:323)
>         at cats.effect.internals.IOShift$Tick.run(IOShift.scala:35)
>         at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.lang.Thread.run(Thread.java:834)
>         at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
>         at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
> ```
> 
> but no issue if I remove the static and muslc... I think my other static image is running just find via ipv4...

I have not seen this before, that is odd indeed. If I understood correctly, it does not happen with a dynamically linked image? Do you by any chance have a reproducer? I also assume this is on the GraalVM 20.0 release?

**Comment by apple-corps** [comment]
I would like to get back to that issue. Also we are discussing two approaches regarding building static images, this and another suggested. https://github.com/http4s/http4s/issues/3299

**Comment by gradinac** [comment]
I have not noticed that you have given me access to modify the PR (my bad!). I have added a warning related to using the system's libstdc++. If you agree with the changes, let me know and we can merge this.

**Comment by apple-corps** [comment]
@gradinac however you want to publish it. Regarding the protocol issue with IPv6. I created a reproduction and pushed here to master : https://github.com/drocsid/https_example . Should we file a bug with graal?

**Review by apple-corps — COMMENTED** [review]
Approve (won't let me select radio button)

**Comment by apple-corps** [comment]
Here's my build system info:

java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)

OS: Debian 4.19.0-4-amd64 bullseye
Architecture: AMD64

**Comment by apple-corps** [comment]
@gradinac I also just built it against your bundle vs the bundle i built from debian sources. I get the same error / stack trace for IPv6. Also the build requires SBT...

**Comment by apple-corps** [comment]
@gradinac do you think we should file a bug report for https://github.com/gradinac/musl-bundle-example/pull/1#issuecomment-615070966

**Comment by gradinac** [comment]
@drocsid Since we have agreed on the changes here, I will merge and close this PR.
As for the ipv6 issue, a GraalVM bug report would be good. Thank you for providing a reproducer for it! I will look into it.

**Comment by apple-corps** [comment]
Here's the report: https://github.com/oracle/graal/issues/2373

**Comment by gradinac** [comment]
Thank you for the report! I have managed to reproduce the error with your repo on the latest master - will dig into it.

**Pull request merged**
